### ISSUE TITLE
Debounce edit_cell requests in client

### ISSUE THREAD

**Issue by baileytincher** [actually-colab/editor#85]
- [ ] use lodash.debounce
- [ ] Add maxWait param. @jtaylorchang any opinions on length?

**Comment by jtaylorchang** [comment]
Maybe we start with like 5 seconds and try values from there with maybe a max of 30?

**Comment by baileytincher** [comment]
I was thinking even lower honestly. 30 would be really slow

**Comment by jtaylorchang** [comment]
That's fair, maybe 10 for a max then? We can play with the value to find something that feels right
